export type CoffeeShop = {
  id: string;
  name: string;
  area: string;
  address: string;
  rating: number;
  reviews: number;
  description: string;
  tags: string[];
  image: string;
  menuUrl: string;
  googleMapsUrl: string;
  lat: number;
  lng: number;
};

export const areas = [
  "All",
  // Municipalities
  "Affton", "Ballwin", "Brentwood", "Chesterfield", "Clayton", "Cottleville", "Creve Coeur", "Ellisville", "Eureka", "Ferguson", "Florissant", "Kirkwood", "Ladue", "Lake St Louis", "Manchester", "Maplewood", "Maryland Heights", "Overland", "Richmond Heights", "St. Ann", "St. Charles", "University City", "Washington, MO", "Webster Groves", "Wentzville", "Wildwood", "Winfield",
  // City Neighborhoods / Areas
  "Benton Park", "Bevo Mill", "Carondelet", "Central West End", "Dogtown", "Downtown", "Fox Park", "High Ridge", "Lafayette Square", "Midtown", "Shaw", "Skinker-DeBaliviere", "Soulard", "South City", "Southampton", "The Hill", "The Loop", "Tower Grove"
];

export const coffeeShops: CoffeeShop[] = [
  // --- ORIGINAL & MAGAZINE PICKS ---
  { id: "1", name: "Sump Coffee", area: "South City", address: "3700 S Jefferson Ave, St. Louis, MO 63118", rating: 4.8, reviews: 1240, description: "Renowned as STL's best specialty roaster. Famous for single-origin pour-overs, salted maple lattes, and breakfast sandwiches. Small-batch roasting on a 10kg Diedrich.", tags: ["Specialty Coffee", "Roaster", "Minimalist"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.sumpcoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Sump+Coffee+St+Louis", lat: 38.5947, lng: -90.2165 },
  { id: "2", name: "Blueprint Coffee", area: "The Loop", address: "6225 Delmar Blvd, St. Louis, MO 63130", rating: 4.7, reviews: 980, description: "Employee-owned roaster known for house-made biscuits, rosemary goat cheese scones, and eggs florentine. Science-led brewing across multiple STL locations.", tags: ["Employee Owned", "Roaster", "Science"], image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=2574&auto=format&fit=crop", menuUrl: "https://blueprintcoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Blueprint+Coffee+Delmar", lat: 38.6554, lng: -90.3015 },
  { id: "3", name: "Comet Coffee", area: "Dogtown", address: "5708 Oakland Ave, St. Louis, MO 63110", rating: 4.9, reviews: 850, description: "Award-winning microbakery famous for flaky croissants that sell out daily, chocolate morning buns, and expertly dialed espresso. Arrive early.", tags: ["Micro-roaster", "Bakery", "Expert"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2547&auto=format&fit=crop", menuUrl: "https://www.cometcoffeestl.com/", googleMapsUrl: "https://maps.google.com/?q=Comet+Coffee+St+Louis", lat: 38.628, lng: -90.2785 },
  { id: "4", name: "Teleo Coffee", area: "Kirkwood", address: "132 W Monroe Ave, Kirkwood, MO 63122", rating: 4.9, reviews: 450, description: "Community-focused cafe known for their Honey Bear Latte, lavender vanilla lattes, coffee flights, and addictive breakfast bagel sandwiches with housemade sauce.", tags: ["Community", "Seasonal", "Cozy"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.teleocoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Teleo+Coffee+Kirkwood", lat: 38.5834, lng: -90.4072 },
  { id: "5", name: "Antagonist Cafe", area: "Soulard", address: "2727 S 12th St, St. Louis, MO 63118", rating: 4.9, reviews: 86, description: "Moody Art Deco gem in a 1937 former police station with jail-cell seating nooks. Houses the in-house roastery and bakery for sister shop Protagonist.", tags: ["Art Deco", "Roaster", "Soulard"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Antagonist+Cafe+Soulard", lat: 38.5997, lng: -90.2114 },
  { id: "6", name: "Protagonist Cafe", area: "Soulard", address: "1700 S 9th St, St. Louis, MO 63104", rating: 4.8, reviews: 640, description: "Literary-themed cafe with 5,000+ books for sale and a 27-foot bookshelf. Serves house-roasted organic coffee, spinach feta croissants, and housemade pastries.", tags: ["Books", "Soulard", "Atmosphere"], image: "https://images.unsplash.com/photo-1521449293024-14b6bbecf57b?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://protagonistcafe.com/", googleMapsUrl: "https://maps.google.com/?q=Protagonist+Cafe+Soulard", lat: 38.6065, lng: -90.2072 },
  { id: "7", name: "23 West Coffee", area: "Webster Groves", address: "23 W Lockwood Ave, Webster Groves, MO 63119", rating: 4.8, reviews: 320, description: "Modern, coffee-first cafe with a La Marzocco espresso machine and LuciAnna's pastries including almond croissants and quiche. Known for espresso tonics.", tags: ["Modern", "Espresso", "Downtown Webster"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=23+West+Coffee+Webster+Groves", lat: 38.5912, lng: -90.352 },
  { id: "8", name: "Maypop Coffee & Garden Shop", area: "Webster Groves", address: "803 Marshall Ave, Webster Groves, MO 63119", rating: 4.8, reviews: 580, description: "Hybrid coffee shop and garden nursery in a charming brick house. Serves Blueprint Coffee, toast plates, and seasonal drinks surrounded by native plants.", tags: ["Plants", "Garden", "Quiet"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.maypopshop.com/", googleMapsUrl: "https://maps.google.com/?q=Maypop+Coffee+Webster+Groves", lat: 38.587, lng: -90.3555 },
  { id: "9", name: "Looking Meadow Café", area: "Maplewood", address: "2500 Sutton Blvd, Maplewood, MO 63143", rating: 4.8, reviews: 150, description: "Plant-based cafe and bakery focusing on locally sourced ingredients. Serves scratch-made vegan pastries, seasonal toasts, and craft coffee in a cozy space.", tags: ["Plant-Based", "Bakery", "Local"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.lookingmeadowcafe.com/", googleMapsUrl: "https://maps.google.com/?q=Looking+Meadow+Cafe+Maplewood", lat: 38.6145, lng: -90.3245 },
  { id: "10", name: "Quarrelsome Coffee", area: "Central West End", address: "3901 Laclede Ave, St. Louis, MO 63108", rating: 4.8, reviews: 210, description: "Permanently closed as of February 2025. Was known for yeast-fermented coffee beans and experimental brewing.", tags: ["Closed"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://quarrelsomecoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Quarrelsome+Coffee+St+Louis", lat: 38.6349, lng: -90.251 },
  { id: "11", name: "Northwest Coffee", area: "Central West End", address: "4251 Laclede Ave, St. Louis, MO 63108", rating: 4.7, reviews: 430, description: "Specializing in organic, small-batch air-roasted coffee since 2006. Serves pastries and light bites with a beautiful dog-friendly patio in the CWE.", tags: ["Organic", "Roaster", "Patio"], image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=2070&auto=format&fit=crop", menuUrl: "http://northwestcoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Northwest+Coffee+Roasting+St+Louis", lat: 38.6349, lng: -90.258 },
  { id: "13", name: "Coma Coffee Roasters", area: "Richmond Heights", address: "1034 S Brentwood Blvd, Richmond Heights, MO 63117", rating: 4.8, reviews: 720, description: "High-design roaster with a full brunch menu including loaded avo toast, mini pancakes, honey chicken tacos, and a smash burger. Plus craft cocktails and beer.", tags: ["Design", "Roaster", "Brunch"], image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=2574&auto=format&fit=crop", menuUrl: "https://www.comacoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Coma+Coffee+Richmond+Heights", lat: 38.624, lng: -90.3475 },
  { id: "14", name: "The Drip Community Coffee House", area: "Tower Grove", address: "3615 Potomac St, St. Louis, MO 63116", rating: 4.9, reviews: 120, description: "Community-focused space near Tower Grove Park. Serves locally roasted coffee, pastries, and light bites in a warm, welcoming neighborhood setting.", tags: ["Community", "Local", "Cozy"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=The+Drip+St+Louis", lat: 38.6084, lng: -90.2575 },
  { id: "15", name: "Hartford Coffee Co.", area: "Tower Grove", address: "3974 Hartford St, St. Louis, MO 63116", rating: 4.7, reviews: 920, description: "Family-friendly cafe since 2004 with a dedicated kids' play area. House air-roasts their beans and serves breakfast sammies, turkey clubs, and gooey butter cake.", tags: ["Family Friendly", "Kid Zone", "Roaster"], image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=2070&auto=format&fit=crop", menuUrl: "http://www.hartfordcoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Hartford+Coffee+Co+St+Louis", lat: 38.6048, lng: -90.262 },
  { id: "16", name: "SweetArt", area: "Shaw", address: "2203 S 39th St, St. Louis, MO 63110", rating: 4.9, reviews: 1100, description: "100% plant-based bakeshop and cafe since 2008. Famous for vegan chik'n sandwiches (featured on Netflix), 32+ cupcake flavors, and scratch-made cinnamon rolls.", tags: ["Vegan", "Art Studio", "Bakery"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "http://sweetartstl.com/", googleMapsUrl: "https://maps.google.com/?q=SweetArt+St+Louis", lat: 38.6131, lng: -90.2636 },
  { id: "17", name: "La Finca Coffee", area: "Eureka", address: "137 S Central Ave, Eureka, MO 63025", rating: 4.9, reviews: 280, description: "STL's first authentic Colombian coffee shop. House-roasts single-origin beans and serves empanadas, patacones, and Colombian lunches in a rustic South American space.", tags: ["Colombian", "Roaster", "Authentic"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.coffeelafinca.com/", googleMapsUrl: "https://maps.google.com/?q=La+Finca+Coffee+Eureka", lat: 38.5005, lng: -90.6346 },
  { id: "20", name: "Pioneer Bakery Cafe", area: "Kirkwood", address: "210 N Kirkwood Rd, Kirkwood, MO 63122", rating: 4.8, reviews: 320, description: "Beloved bakery and cafe employing people with developmental disabilities. Known for fresh-baked pastries, breakfast sandwiches, and their mission-driven community spirit.", tags: ["Social Good", "Bakery", "Breakfast"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Pioneer+Bakery+Cafe+Kirkwood", lat: 38.5863, lng: -90.4069 },
  { id: "22", name: "Ari's Light", area: "Southampton", address: "4647 Hampton Ave, St. Louis, MO 63109", rating: 4.9, reviews: 95, description: "Bright, welcoming cafe serving craft coffee, specialty teas, and fresh pastries. Known for their warm hospitality and vibrant energy on Hampton Ave.", tags: ["Craft Coffee", "Tea", "Vibrant"], image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=2070&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Aris+Light+St+Louis", lat: 38.597, lng: -90.2835 },
  { id: "24", name: "Deer Creek Coffee", area: "Ladue", address: "9820 Clayton Rd, Ladue, MO 63124", rating: 4.7, reviews: 450, description: "Neighborhood favorite since 2012 with house-roasted beans and a full breakfast/lunch menu including sandwiches, salads, and baked goods. Great outdoor patio in Ladue.", tags: ["Roaster", "Kitchen", "Ladue"], image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://deercreekcoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Deer+Creek+Coffee+Ladue", lat: 38.6342, lng: -90.3842 },
  { id: "25", name: "Exit 11 Coffee", area: "Brentwood", address: "2944 S Brentwood Blvd, Brentwood, MO 63144", rating: 4.8, reviews: 180, description: "Charming drive-thru coffee cabin serving high-quality craft espresso, cold brew, and seasonal drinks on the go. Quick, friendly service with locally sourced beans.", tags: ["Drive-Thru", "Craft Coffee", "Convenient"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://exit11coffee.com/", googleMapsUrl: "https://maps.google.com/?q=Exit+11+Coffee+Brentwood", lat: 38.6115, lng: -90.3476 },
  { id: "27", name: "Latte Lounge", area: "Florissant", address: "2190 N Waterford Dr, Florissant, MO 63033", rating: 4.7, reviews: 350, description: "North County gem famous for creative split-cup lattes, latte flights, and swing-at-the-bar seating. Serves pastries, smoothies, and specialty drinks in a fun atmosphere.", tags: ["Swings", "Community", "North County"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://latteloungestl.com/", googleMapsUrl: "https://maps.google.com/?q=Latte+Lounge+Florissant", lat: 38.7891, lng: -90.3411 },
  { id: "30", name: "CoffeeStamp", area: "Fox Park", address: "2511 S Jefferson Ave, St. Louis, MO 63104", rating: 4.9, reviews: 410, description: "Founded by Honduran brothers roasting incredible single-origin coffees on-site. Serves house-made empanadas, breakfast burritos, and Latin-inspired pastries.", tags: ["Honduran", "Roaster", "Brothers"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.coffeestamp.com/", googleMapsUrl: "https://maps.google.com/?q=Coffeestamp+St+Louis", lat: 38.6053, lng: -90.2171 },
  { id: "31", name: "Living Room", area: "Maplewood", address: "2810 Sutton Blvd, Maplewood, MO 63143", rating: 4.8, reviews: 420, description: "Social enterprise cafe known for incredible fresh-baked sourdough, pour-overs, and their mobile 'Coffee Descartes' cart. All profits support community programs.", tags: ["Social Good", "Bakery", "Pour-over"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "http://www.livingroomstl.com/", googleMapsUrl: "https://maps.google.com/?q=Living+Room+Maplewood", lat: 38.6147, lng: -90.321 },
  { id: "32", name: "Crave Coffee House", area: "Midtown", address: "3504 Caroline St, St. Louis, MO 63104", rating: 4.7, reviews: 180, description: "Nonprofit cafe inside a historic church, with all proceeds supporting local children's hospitals. Serves espresso, pastries, and sandwiches for a cause.", tags: ["Nonprofit", "Historic", "Community"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "http://cravestl.org/", googleMapsUrl: "https://maps.google.com/?q=Crave+Coffee+House+St+Louis", lat: 38.6245, lng: -90.22 },
  { id: "33", name: "Catalyst Coffee Bar", area: "Downtown", address: "1223 Pine St, St. Louis, MO 63103", rating: 4.8, reviews: 110, description: "Art-focused cafe inside Art St. Louis gallery. Every latte purchase supports local painters and sculptors. Serves espresso drinks and baked goods.", tags: ["Art", "Gallery", "Espresso"], image: "https://images.unsplash.com/photo-1521449293024-14b6bbecf57b?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://catalyst-coffee-bar.square.site/", googleMapsUrl: "https://maps.google.com/?q=Catalyst+Coffee+Bar+St+Louis", lat: 38.6301, lng: -90.1976 },
  { id: "34", name: "Shameless Grounds", area: "Benton Park", address: "1901 Withnell Ave, St. Louis, MO 63118", rating: 4.7, reviews: 380, description: "Radically inclusive LGBTQ+-friendly cafe with a lending library of 3,000+ books. Serves fair-trade coffee, chai, pastries, and hosts community events.", tags: ["Inclusive", "Books", "LGBTQ+ Friendly"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "http://shamelessgrounds.com/", googleMapsUrl: "https://maps.google.com/?q=Shameless+Grounds+St+Louis", lat: 38.5994, lng: -90.215 },
  { id: "35", name: "Meshuggah Café", area: "The Loop", address: "6269 Delmar Blvd, St. Louis, MO 63130", rating: 4.6, reviews: 520, description: "A Delmar Loop institution for over 25 years. Famous for their cinnamon scones, chai, and being a late-night hangout spot for artists and musicians.", tags: ["Historic", "Loop", "Scones"], image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://meshuggahonline.square.site/", googleMapsUrl: "https://maps.google.com/?q=Meshuggah+Cafe+St+Louis", lat: 38.6555, lng: -90.302 },
  { id: "36", name: "Shaw's Coffee", area: "The Hill", address: "5147 Shaw Ave, St. Louis, MO 63110", rating: 4.7, reviews: 440, description: "Classic coffeehouse since 1993 with a massive Probat roaster on display. Known for their proprietary blends, fresh muffins, and cozy patio on The Hill.", tags: ["Roaster", "Classic", "The Hill"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "http://www.shawscoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Shaws+Coffee+St+Louis", lat: 38.6168, lng: -90.2735 },
  { id: "37", name: "MoKaBe's Coffeehouse", area: "Tower Grove", address: "3606 Arsenal St, St. Louis, MO 63116", rating: 4.6, reviews: 890, description: "South Grand stalwart since 1993 with a legendary Sunday brunch buffet, housemade baked goods, and a beloved patio. Open late for night owls.", tags: ["Patio", "Brunch", "Late Night"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.facebook.com/mokabes/", googleMapsUrl: "https://maps.google.com/?q=MoKaBes+Coffeehouse+St+Louis", lat: 38.6027, lng: -90.2488 },
  { id: "38", name: "Maplewood Deli & Coffeehouse", area: "Maplewood", address: "7298 Manchester Rd, Maplewood, MO 63143", rating: 4.5, reviews: 210, description: "Cozy neighborhood spot with a massive pastry case, all-day breakfast, deli sandwiches, and locally roasted coffee. A Maplewood staple.", tags: ["Deli", "Pastries", "Maplewood"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.maplewooddeliandcoffeehouse.com/", googleMapsUrl: "https://maps.google.com/?q=Maplewood+Deli+Coffeehouse", lat: 38.614, lng: -90.3235 },
  { id: "39", name: "The Washington Coffeeshop", area: "Washington, MO", address: "2 E 5th St, Washington, MO 63090", rating: 4.8, reviews: 150, description: "Charming cafe in a historic building near the riverfront. Serves espresso, pastries, sandwiches, and smoothies. Perfect for a Missouri wine country stop.", tags: ["Historic", "Riverfront", "Cozy"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "http://www.thewashingtoncoffeeshop.com/", googleMapsUrl: "https://maps.google.com/?q=The+Washington+Coffeeshop+MO", lat: 38.5574, lng: -91.012 },
  { id: "40", name: "The Annex Coffee & Foods", area: "Webster Groves", address: "8122 Big Bend Blvd, Webster Groves, MO 63119", rating: 4.8, reviews: 290, description: "Curated local market and cafe serving award-winning coffee, artisan sandwiches, charcuterie boards, and craft cocktails in a rustic Webster Groves space.", tags: ["Market", "Cocktails", "Local"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.theannexstl.com/", googleMapsUrl: "https://maps.google.com/?q=The+Annex+Webster+Groves", lat: 38.589, lng: -90.34 },
  { id: "41", name: "Bike Stop Café", area: "Chesterfield", address: "17057 N Outer 40 Rd, Chesterfield, MO 63005", rating: 4.7, reviews: 180, description: "Cyclist-friendly cafe on the Katy Trail serving from-scratch baked goods, breakfast sandwiches, smoothies, and fresh coffee. Mini bike repair station on site.", tags: ["Cycling", "Health", "Bakery"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "http://www.bikestopcafes.com/", googleMapsUrl: "https://maps.google.com/?q=Bike+Stop+Cafe+Chesterfield", lat: 38.6625, lng: -90.5565 },
  { id: "43", name: "Fiddlehead Fern Café", area: "Shaw", address: "4066 Russell Blvd, St. Louis, MO 63110", rating: 4.9, reviews: 650, description: "Woman-owned, all-vegetarian cafe near MoBot with botanical-inspired decor. Known for avocado toast, goat cheese croissants, cold-pressed juices, and Modbar espresso.", tags: ["Botanical", "Modbar", "Aesthetic"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "http://fiddleheadferncafe.com/home.html", googleMapsUrl: "https://maps.google.com/?q=Fiddlehead+Fern+Cafe+St+Louis", lat: 38.6129, lng: -90.2622 },
  { id: "44", name: "LC Coffee Roasters", area: "Maplewood", address: "7360 Manchester Rd, Maplewood, MO 63143", rating: 4.8, reviews: 220, description: "Small-batch Latin American roastery offering nitro cold brew, flash-brewed Japanese iced coffee, and pastries. Beans sourced directly from family farms.", tags: ["Roaster", "Nitro", "Flash Brew"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.lacosechacoffee.com/", googleMapsUrl: "https://maps.google.com/?q=LC+Coffee+Roasters+Maplewood", lat: 38.6142, lng: -90.325 },
  { id: "45", name: "Course Coffee Roasters", area: "St. Charles", address: "1360 S 5th St, St. Charles, MO 63301", rating: 4.9, reviews: 180, description: "Micro-roastery and coffee bar in Frenchtown, St. Charles. Known for single-origin pour-overs, espresso flights, and fresh pastries in a cozy neighborhood setting.", tags: ["Discovery", "Roaster", "Frenchtown"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.coursecoffeeroasters.com/", googleMapsUrl: "https://maps.google.com/?q=Course+Coffee+Roasters+St+Charles", lat: 38.779, lng: -90.4805 },

  // --- KALDI'S LOCATIONS ---
  { id: "k1", name: "Kaldi's Coffee - DeMun", area: "Clayton", address: "700 DeMun Ave, St. Louis, MO 63105", rating: 4.7, reviews: 2100, description: "The original 1994 Kaldi's location overlooking Concordia Park. STL's beloved coffee institution serves house-roasted beans, fresh pastries, and breakfast items.", tags: ["Original", "Historic", "Outdoor Seating"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2671&auto=format&fit=crop", menuUrl: "https://kaldiscoffee.com/pages/demun", googleMapsUrl: "https://maps.google.com/?q=Kaldis+Coffee+DeMun", lat: 38.6217, lng: -90.2932 },
  { id: "k2", name: "Kaldi's Coffee - Kayak's", area: "Skinker-DeBaliviere", address: "270 N Skinker Blvd, St. Louis, MO 63130", rating: 4.6, reviews: 850, description: "Rustic, lodge-themed cafe next to Washington University. Popular study spot serving Kaldi's house-roasted coffee, pastries, and seasonal drinks.", tags: ["Study Spot", "Lodge Vibes", "WashU"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://kaldiscoffee.com/pages/kayaks", googleMapsUrl: "https://maps.google.com/?q=Kaldis+Coffee+Kayaks", lat: 38.6512, lng: -90.301 },
  { id: "k3", name: "Kaldi's Coffee - Kirkwood", area: "Kirkwood", address: "120 S Kirkwood Rd, Kirkwood, MO 63122", rating: 4.7, reviews: 620, description: "Bustling downtown Kirkwood spot with a spacious patio. Serves Kaldi's full menu of house-roasted espresso, teas, pastries, and breakfast sandwiches.", tags: ["Patio", "Bustling", "Downtown Kirkwood"], image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=2070&auto=format&fit=crop", menuUrl: "https://kaldiscoffee.com/pages/kirkwood", googleMapsUrl: "https://maps.google.com/?q=Kaldis+Coffee+Kirkwood", lat: 38.5835, lng: -90.4065 },
  { id: "k4", name: "Kaldi's Coffee - CWE", area: "Central West End", address: "52 N Euclid Ave, St. Louis, MO 63108", rating: 4.6, reviews: 480, description: "Elegant, light-filled CWE cafe serving Kaldi's house-roasted coffee, fresh pastries, and seasonal specialty drinks in a refined neighborhood setting.", tags: ["Modern", "CWE", "Light-filled"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://kaldiscoffee.com/pages/central-west-end", googleMapsUrl: "https://maps.google.com/?q=Kaldis+Coffee+Central+West+End", lat: 38.6396, lng: -90.2615 },
  { id: "k5", name: "Kaldi's Coffee - Chesterfield", area: "Chesterfield", address: "1668 Clarkson Rd, Chesterfield, MO 63017", rating: 4.5, reviews: 310, description: "Spacious West County location ideal for remote work. Full menu of Kaldi's house-roasted beans, espresso drinks, teas, and baked goods.", tags: ["Spacious", "Work Friendly", "Chesterfield"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://kaldiscoffee.com/pages/chesterfield", googleMapsUrl: "https://maps.google.com/?q=Kaldis+Coffee+Chesterfield", lat: 38.6423, lng: -90.5498 },
  { id: "k6", name: "Kaldi's Coffee - Citygarden", area: "Downtown", address: "808 Chestnut St, St. Louis, MO 63101", rating: 4.6, reviews: 240, description: "Stunning glass-walled cafe within Citygarden sculpture park downtown. Enjoy Kaldi's coffee and pastries with beautiful views of the park.", tags: ["Park Views", "Downtown", "Modern"], image: "https://images.unsplash.com/photo-1521449293024-14b6bbecf57b?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://kaldiscoffee.com/pages/citygarden", googleMapsUrl: "https://maps.google.com/?q=Kaldis+Coffee+Citygarden", lat: 38.628, lng: -90.192 },
  { id: "k7", name: "Kaldi's Coffee - Mid-Campus", area: "Midtown", address: "4515 McKinley Ave, St. Louis, MO 63110", rating: 4.7, reviews: 150, description: "Quick, professional service for the WashU Medical campus community. Full Kaldi's espresso menu and grab-and-go pastries and snacks.", tags: ["Fast Service", "Medical Campus", "Modern"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://kaldiscoffee.com/pages/mid-campus-center", googleMapsUrl: "https://maps.google.com/?q=Kaldis+Coffee+Mid+Campus", lat: 38.6337, lng: -90.2588 },
  { id: "k8", name: "Kaldi's Coffee - Farrell Learning Center", area: "Central West End", address: "520 S Euclid Ave, St. Louis, MO 63110", rating: 4.6, reviews: 90, description: "Sleek campus cafe inside WashU Medical School's Farrell Learning Center. Serves Kaldi's full espresso and tea menu with quick grab-and-go options.", tags: ["Campus", "Convenient", "Sleek"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://kaldiscoffee.com/pages/farrell-learning-center", googleMapsUrl: "https://maps.google.com/?q=Kaldis+Coffee+Farrell+Learning+Center", lat: 38.6345, lng: -90.262 },

  // --- CSV SUPPLEMENTAL ---
  { id: "a1", name: "Coffee Culture", area: "Affton", address: "8909 Gravois Rd, St. Louis, MO 63123", rating: 4.7, reviews: 110, description: "Cozy Affton spot serving locally roasted coffee, fresh pastries, and light breakfast items. A welcoming neighborhood hangout with friendly regulars.", tags: ["Cozy", "Local", "Affton"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Coffee+Culture+Affton", lat: 38.5473, lng: -90.3332 },
  { id: "a2", name: "Sedara Sweets & Ice Cream", area: "Affton", address: "9223 Gravois Rd, St. Louis, MO 63123", rating: 4.8, reviews: 350, description: "Mediterranean-inspired cafe famous for authentic baklava, Turkish coffee, kunafa, and ice cream. A sweet haven with Middle Eastern flavors in Affton.", tags: ["Mediterranean", "Turkish Coffee", "Sweets"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Sedara+Sweets+Affton", lat: 38.5425, lng: -90.341 },
  { id: "b1", name: "The Wolf", area: "Ballwin", address: "15480 Clayton Rd, Ballwin, MO 63011", rating: 4.7, reviews: 820, description: "Sustainability-focused cafe and taproom serving craft coffee, local beer, seasonal sandwiches, and house-made baked goods. A vibrant West County community hub.", tags: ["Sustainable", "Craft Beer", "Eco-friendly"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.thewolfstl.com/", googleMapsUrl: "https://maps.google.com/?q=The+Wolf+Ballwin", lat: 38.5917, lng: -90.5506 },
  { id: "bp1", name: "Cheshire Grin Cat Cafe", area: "Benton Park", address: "1926 Cherokee St, St. Louis, MO 63118", rating: 4.8, reviews: 120, description: "Sip coffee while hanging out with adoptable cats on historic Cherokee Street. Serves espresso drinks, teas, and pastries in a playful, unique atmosphere.", tags: ["Cat Cafe", "Cherokee Street", "Community"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Cheshire+Grin+Cat+Cafe", lat: 38.5978, lng: -90.2215 },
  { id: "bp2", name: "The Mud House", area: "Benton Park", address: "2101 Cherokee St, St. Louis, MO 63118", rating: 4.7, reviews: 1450, description: "Iconic Cherokee Street brunch destination with a stunning hidden patio. Famous for hearty breakfast plates, locally roasted coffee, and a lively weekend atmosphere.", tags: ["Brunch", "Patio", "Cherokee Street"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "http://themudhousestl.com/", googleMapsUrl: "https://maps.google.com/?q=The+Mud+House+St+Louis", lat: 38.5978, lng: -90.218 },
  { id: "bv1", name: "Arber Cafe", area: "Bevo Mill", address: "6955 Gravois Ave, St. Louis, MO 63116", rating: 4.8, reviews: 140, description: "Albanian-inspired cafe in Bevo Mill serving incredible homemade desserts like trilece and baklava alongside specialty espresso drinks and Turkish coffee.", tags: ["Albanian", "Desserts", "Bevo Mill"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Arber+Cafe+St+Louis", lat: 38.5736, lng: -90.268 },
  { id: "ca1", name: "Speakeasy Cafe", area: "Carondelet", address: "527 Holly Hills Ave, St. Louis, MO 63111", rating: 4.8, reviews: 210, description: "Charming Holly Hills cafe serving premium locally roasted coffee, fresh-baked scones, muffins, and breakfast sandwiches. A beloved Carondelet neighborhood gathering spot.", tags: ["Baked Goods", "Neighborhood", "Holly Hills"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Speakeasy+Cafe+St+Louis", lat: 38.5764, lng: -90.2632 },
  { id: "ca2", name: "Zoomies Pet Cafe", area: "Carondelet", address: "5838 Macklind Ave, St. Louis, MO 63109", rating: 4.9, reviews: 85, description: "Adorable dog-friendly pet cafe where pups play while owners enjoy locally roasted coffee, lattes, and light bites. Pupcake treats and doggy menu available too.", tags: ["Dog Friendly", "Pet Cafe", "Community"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Zoomies+Pet+Cafe+St+Louis", lat: 38.5845, lng: -90.281 },
  { id: "cl1", name: "Cafe Brevé", area: "Clayton", address: "120 S Central Ave, Clayton, MO 63105", rating: 4.6, reviews: 95, description: "Polished Clayton cafe serving specialty espresso drinks, cold brew, and light pastries. A popular morning stop for the downtown business district crowd.", tags: ["Specialty", "Clayton", "Business"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Cafe+Breve+Clayton", lat: 38.6425, lng: -90.3375 },
  { id: "cl2", name: "City Coffeehouse + Crêperie", area: "Clayton", address: "36 N Brentwood Blvd, Clayton, MO 63105", rating: 4.7, reviews: 1250, description: "Clayton classic famous for authentic sweet and savory crepes, perfectly paired with espresso drinks and fresh-squeezed juices. A longtime neighborhood favorite.", tags: ["Crepes", "Clayton", "Classic"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=City+Coffeehouse+Clayton", lat: 38.6439, lng: -90.3468 },
  { id: "cl3", name: "Ivy Cafe", area: "Clayton", address: "14 N Meramec Ave, Clayton, MO 63105", rating: 4.8, reviews: 180, description: "Chic Clayton cafe known for beautifully plated gourmet tartines, artisanal lattes, and seasonal salads. A stylish lunch and coffee destination with European flair.", tags: ["Tartines", "Chic", "Lattes"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Ivy+Cafe+Clayton", lat: 38.644, lng: -90.338 },
  { id: "cc1", name: "Gateway Coffee Company", area: "Creve Coeur", address: "11377 Olive Blvd, Creve Coeur, MO 63141", rating: 4.7, reviews: 120, description: "Sleek West County cafe with expertly pulled espresso, pour-overs, fresh-baked muffins, and seasonal drinks. A modern gathering spot on Olive Blvd in Creve Coeur.", tags: ["Espresso", "Modern", "West County"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Gateway+Coffee+Creve+Coeur", lat: 38.6575, lng: -90.4245 },
  { id: "cc2", name: "The Ground Coffee House & Plant Shop", area: "Creve Coeur", address: "12599 Olive Blvd, Creve Coeur, MO 63141", rating: 4.8, reviews: 85, description: "Lush green oasis combining a plant shop with a specialty coffee bar. Enjoy craft lattes, teas, and pastries surrounded by houseplants and succulents in Creve Coeur.", tags: ["Plants", "Greenhouse", "Specialty"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=The+Ground+Creve+Coeur", lat: 38.6575, lng: -90.4445 },
  { id: "cc3", name: "Revocup Coffee", area: "Creve Coeur", address: "11669 Ladue Rd, Creve Coeur, MO 63141", rating: 4.7, reviews: 310, description: "Ethically sourced Ethiopian coffee roasted in-house with traditional preparation methods. Serves single-origin pour-overs, espresso, and light bites in Creve Coeur.", tags: ["Ethiopian", "Ethical", "West County"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Revocup+Coffee+Creve+Coeur", lat: 38.6505, lng: -90.4305 },
  { id: "dt1", name: "Crema Coffeehouse", area: "Dogtown", address: "275 Union Blvd, St. Louis, MO 63108", rating: 4.8, reviews: 240, description: "Cozy Dogtown cafe near Forest Park serving fair-trade coffee, from-scratch croissants, muffins, and breakfast sandwiches. A warm neighborhood staple with loyal regulars.", tags: ["Fair Trade", "Pastries", "Forest Park"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Crema+Coffeehouse+St+Louis", lat: 38.6405, lng: -90.262 },
  { id: "f1", name: "Hive Cafe", area: "Ferguson", address: "235 S Florissant Rd, Ferguson, MO 63135", rating: 4.8, reviews: 150, description: "Warm downtown Ferguson cafe serving locally roasted coffee, hearty breakfast plates, sandwiches, and fresh-baked pastries. A welcoming community gathering spot.", tags: ["Breakfast", "Ferguson", "Community"], image: "https://images.unsplash.com/photo-1521449293024-14b6bbecf57b?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Hive+Cafe+Ferguson", lat: 38.7442, lng: -90.3053 },
  { id: "ls1", name: "E61 Cafe", area: "Lafayette Square", address: "307 Belt Ave, St. Louis, MO 63112", rating: 4.8, reviews: 95, description: "Intimate cafe specializing in authentic Greek coffee, freddo espresso, and specialty loose-leaf teas. A hidden gem with Mediterranean charm near Lafayette Square.", tags: ["Greek Coffee", "Specialty Tea", "Lafayette Square"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=E61+Cafe+St+Louis", lat: 38.6478, lng: -90.2685 },
  { id: "m1", name: "Mauhaus Cat Cafe", area: "Maplewood", address: "3101 Sutton Blvd, Maplewood, MO 63143", rating: 4.9, reviews: 420, description: "Beautifully designed Maplewood cat cafe where you can cuddle adoptable rescue cats while sipping premium espresso, lattes, and teas. Pastries and cat-themed treats available.", tags: ["Cat Cafe", "Maplewood", "Community"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://mauhauscafe.com/", googleMapsUrl: "https://maps.google.com/?q=Mauhaus+Cat+Cafe", lat: 38.6148, lng: -90.32 },
  { id: "sc1", name: "Songbird", area: "South City", address: "3153 Morgan Ford Rd, St. Louis, MO 63116", rating: 4.9, reviews: 580, description: "Beloved South City cafe famous for incredible breakfast sandwiches on house-baked bread, high-quality locally roasted coffee, and seasonal specials on Morgan Ford Rd.", tags: ["Breakfast", "Morgan Ford", "Local"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Songbird+St+Louis", lat: 38.5985, lng: -90.2485 },
  { id: "uc1", name: "Zensia", area: "University City", address: "6665 Olive Blvd, University City, MO 63130", rating: 4.7, reviews: 85, description: "Serene U City cafe with an extensive tea menu featuring rare loose-leaf varieties alongside specialty espresso and pour-over coffee. A peaceful retreat on Olive Blvd.", tags: ["Tea", "Serene", "U City"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Zensia+University+City", lat: 38.6626, lng: -90.338 },

  // --- NEW CSV & MAP ADDITIONS ---
  { id: "csv2", name: "Toasted Coffee House", area: "High Ridge", address: "3015 High Ridge Blvd, High Ridge, MO 63049", rating: 4.8, reviews: 150, description: "Friendly High Ridge roaster serving fresh-roasted coffee, seasonal specialty lattes, smoothies, and baked goods. A cozy stop for the south-of-44 community.", tags: ["Roaster", "Seasonal", "Ballwin Area"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Toasted+Coffee+House+High+Ridge", lat: 38.4588, lng: -90.5332 },
  { id: "csv4", name: "Coffee Club", area: "Central West End", address: "4818 Washington Ave, St. Louis, MO 63108", rating: 4.7, reviews: 85, description: "Vibrant CWE cafe serving handcrafted espresso drinks, cold brew, artisanal pastries, and light snacks. A colorful neighborhood hangout on Washington Ave.", tags: ["Handcrafted", "Snacks", "CWE"], image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Coffee+Club+CWE", lat: 38.6375, lng: -90.2505 },
  { id: "csv5", name: "Left Bank Books Cafe", area: "Central West End", address: "399 N Euclid Ave, St. Louis, MO 63108", rating: 4.8, reviews: 320, description: "Charming cafe tucked inside STL's iconic independent bookstore. Browse new releases while enjoying espresso, tea, and pastries in a literary CWE setting.", tags: ["Books", "Literary", "CWE"], image: "https://images.unsplash.com/photo-1521449293024-14b6bbecf57b?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Left+Bank+Books+CWE", lat: 38.643, lng: -90.2615 },
  { id: "csv6", name: "Colleen's Cafe", area: "Clayton", address: "7337 Forsyth Blvd, Clayton, MO 63105", rating: 4.7, reviews: 850, description: "Bustling Clayton cafe beloved for scratch-made scones, cinnamon rolls, and hearty egg sandwiches alongside quality espresso. A Forsyth Blvd morning institution.", tags: ["Bakery", "Breakfast", "Clayton"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Colleens+Cafe+Clayton", lat: 38.6465, lng: -90.342 },
  { id: "csv7", name: "Seedz Provisions", area: "Clayton", address: "6344 S Rosebury Ave, Clayton, MO 63105", rating: 4.8, reviews: 320, description: "Upscale vegan cafe and market serving plant-based bowls, salads, smoothies, and a curated specialty coffee program. A Clayton destination for health-conscious foodies.", tags: ["Vegan", "Plant-based", "Specialty"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Seedz+Provisions+Clayton", lat: 38.6388, lng: -90.3218 },
  { id: "csv8", name: "Germania Coffee Haus", area: "Clayton", address: "7701 Forsyth Blvd, Clayton, MO 63105", rating: 4.7, reviews: 150, description: "German-inspired coffee house on Forsyth Blvd serving traditional European-style brews, strudel, pretzels, and specialty lattes in a warm, modern atmosphere.", tags: ["German-style", "Clayton", "Modern"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Germania+Coffee+Haus+Clayton", lat: 38.6465, lng: -90.3488 },
  { id: "csv9", name: "Black Lab", area: "Central West End", address: "631 N Euclid Ave, St. Louis, MO 63108", rating: 4.8, reviews: 110, description: "Cozy, modern CWE cafe serving locally roasted coffee, espresso drinks, and pastries with a welcoming pet-friendly patio. A neighborhood favorite on Euclid Ave.", tags: ["Cozy", "Local Roasts", "Pet-friendly"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Black+Lab+CWE", lat: 38.6452, lng: -90.261 },
  { id: "csv10", name: "Ethio Coffee", area: "Creve Coeur", address: "12644 Olive Blvd, Creve Coeur, MO 63141", rating: 4.9, reviews: 65, description: "Authentic Ethiopian coffee house offering traditional jebena-brewed coffee, single-origin beans, and East African teas. A cultural experience with rich flavors in Creve Coeur.", tags: ["Ethiopian", "Traditional", "Specialty"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Ethio+Coffee+Creve+Coeur", lat: 38.6575, lng: -90.445 },
  { id: "csv11", name: "La Bonne Bouchée Patisserie & Cafe", area: "Creve Coeur", address: "12344 Olive Blvd, Creve Coeur, MO 63141", rating: 4.8, reviews: 1850, description: "Iconic STL French patisserie since 1979 serving exquisite croissants, macarons, tarts, and quiche alongside rich Parisian-style espresso and cafe au lait.", tags: ["French", "Patisserie", "Classic"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=La+Bonne+Bouchee+Creve+Coeur", lat: 38.6575, lng: -90.44 },
  { id: "csv13", name: "Cafe de Blaire", area: "Downtown", address: "442 N 4th St, St. Louis, MO 63102", rating: 4.6, reviews: 90, description: "Trendy downtown cafe offering colorful bubble tea, acai bowls, smoothies, and handcrafted espresso drinks. A fun, Instagram-worthy spot near Laclede's Landing.", tags: ["Bubble Tea", "Acai", "Modern"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Cafe+de+Blaire+St+Louis", lat: 38.6345, lng: -90.1895 },
  { id: "csv14", name: "Java Plus Cafe", area: "Downtown", address: "211 N Broadway, St. Louis, MO 63102", rating: 4.5, reviews: 320, description: "Reliable downtown cafe serving quality espresso, breakfast bagels, deli sandwiches, and salads. A go-to morning stop for the Broadway business corridor.", tags: ["Quick Service", "Lunch", "Downtown"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Java+Plus+Cafe+St+Louis", lat: 38.632, lng: -90.188 },
  { id: "csv15", name: "Cafe Amalia", area: "Kirkwood", address: "10907 Manchester Rd, Kirkwood, MO 63122", rating: 4.8, reviews: 150, description: "Mediterranean-inspired Kirkwood cafe serving Turkish coffee, cardamom lattes, authentic baklava, and savory pastries. A warm cultural experience on Manchester Rd.", tags: ["Mediterranean", "Specialty", "Kirkwood"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Cafe+Amalia+Kirkwood", lat: 38.5838, lng: -90.421 },
  { id: "csv16", name: "Gelato Di Riso", area: "Kirkwood", address: "151 W Jefferson Ave, Kirkwood, MO 63122", rating: 4.9, reviews: 450, description: "Beloved downtown Kirkwood gelato shop with a superb Italian espresso bar. Serves authentic gelato, affogatos, cappuccinos, and classic Italian pastries.", tags: ["Gelato", "Italian", "Espresso Bar"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Gelato+Di+Riso+Kirkwood", lat: 38.585, lng: -90.4075 },
  { id: "csv17", name: "Park Avenue Coffee", area: "Lafayette Square", address: "1919 Park Ave, St. Louis, MO 63104", rating: 4.7, reviews: 1100, description: "STL institution famous for air-roasted coffee and over a dozen flavors of authentic gooey butter cake. Serves espresso, breakfast, and lunch in historic Lafayette Square.", tags: ["Air-roasted", "Gooey Butter Cake", "Lafayette Square"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Park+Avenue+Coffee+Lafayette+Square", lat: 38.613, lng: -90.215 },
  { id: "csv18", name: "Kentzo Koffee", area: "Maplewood", address: "2500 Sutton Ave, Maplewood, MO 63143", rating: 4.7, reviews: 110, description: "Precision-focused Maplewood roastery serving expertly roasted single-origin beans, espresso flights, and pour-overs. A craft coffee lover's paradise on Sutton Ave.", tags: ["Roastery", "Precision", "Maplewood"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Kentzo+Koffee+Maplewood", lat: 38.6145, lng: -90.3245 },
  { id: "csv19", name: "Foundation Grounds", area: "Maplewood", address: "7298 Manchester Rd, Maplewood, MO 63143", rating: 4.7, reviews: 580, description: "Eco-conscious Maplewood cafe with plenty of outlets and WiFi, serving sustainably sourced coffee, fresh pastries, and light lunch options. Ideal for remote work.", tags: ["Sustainable", "Work Friendly", "Maplewood"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Foundation+Grounds+Maplewood", lat: 38.614, lng: -90.323 },
  { id: "csv20", name: "Omen Coffee", area: "Midtown", address: "2647 Washington Ave, St. Louis, MO 63103", rating: 4.9, reviews: 150, description: "Faith-driven roastery and cafe with a beautifully designed interior on Washington Ave. Serves house-roasted espresso, pour-overs, pastries, and light bites in a peaceful Midtown setting.", tags: ["Peaceful", "Roastery", "Midtown"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://omencoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Omen+Coffee+St+Louis", lat: 38.634, lng: -90.2165 },
  { id: "csv25", name: "Winslow’s Table", area: "University City", address: "7213 Delmar Blvd, University City, MO 63130", rating: 4.8, reviews: 1100, description: "Farm-to-table market and cafe on Delmar Blvd serving locally sourced breakfast, lunch, artisan groceries, and a dedicated specialty coffee and espresso program.", tags: ["Farm-to-table", "Market", "Specialty"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.winslowstable.com/", googleMapsUrl: "https://maps.google.com/?q=Winslows+Table+St+Louis", lat: 38.6559, lng: -90.314 },
  { id: "csv26", name: "The Clover and The Bee", area: "Webster Groves", address: "100 W Lockwood Ave, Webster Groves, MO 63119", rating: 4.8, reviews: 850, description: "Artistic, Italian-inspired Webster Groves cafe serving elevated egg dishes, ricotta toast, house-made pastries, and gourmet espresso drinks in a beautifully designed space.", tags: ["Italian-inspired", "Aesthetic", "Elevated"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "http://thecloverandthebee.com/", googleMapsUrl: "https://maps.google.com/?q=The+Clover+and+The+Bee+Webster+Groves", lat: 38.5912, lng: -90.354 },
  { id: "csv27", name: "Webster Groves Garden Café", area: "Webster Groves", address: "117 E Lockwood Ave, Webster Groves, MO 63119", rating: 4.7, reviews: 120, description: "Charming Webster Groves cafe with a lush garden patio, serving locally roasted coffee, fresh-squeezed juices, seasonal salads, and house-baked treats. Perfect for a relaxing afternoon.", tags: ["Garden", "Peaceful", "Neighborhood"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Webster+Groves+Garden+Cafe", lat: 38.591, lng: -90.3505 },

  // --- THE HILL ADDITIONS ---
  { id: "h1", name: "Café Dolce", area: "The Hill", address: "5132 Shaw Ave, St. Louis, MO 63110", rating: 4.8, reviews: 420, description: "A cozy Italian coffeehouse in STL's famous Hill neighborhood serving rich espresso, cappuccinos, cannoli, biscotti, and seasonal Italian sodas. A taste of Italy on Shaw Ave.", tags: ["Italian", "Authentic", "Cozy"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Cafe+Dolce+St+Louis", lat: 38.6168, lng: -90.2745 },
  { id: "h2", name: "Park Avenue Coffee - The Hill", area: "The Hill", address: "5105 Southwest Ave, St. Louis, MO 63110", rating: 4.7, reviews: 310, description: "The Hill outpost of STL's beloved Park Avenue Coffee, serving signature air-roasted coffee and over a dozen flavors of famous gooey butter cake alongside espresso and breakfast.", tags: ["Air-roasted", "Gooey Butter Cake", "Vibrant"], image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=2070&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Park+Avenue+Coffee+The+Hill", lat: 38.6152, lng: -90.274 },
  { id: "h3", name: "MountainHouse Cafe - The Hill", area: "The Hill", address: "2300 Edwards St, St. Louis, MO 63110", rating: 4.8, reviews: 150, description: "Adventure-themed cafe on The Hill serving craft espresso, seasonal lattes, acai bowls, and fresh sandwiches. High-energy atmosphere with outdoor murals and a welcoming vibe.", tags: ["Adventure", "Craft Coffee", "The Hill"], image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=MountainHouse+Cafe+The+Hill", lat: 38.6175, lng: -90.279 },
  { id: "h4", name: "Marconi Mercato", area: "The Hill", address: "2201 Marconi Ave, St. Louis, MO 63110", rating: 4.9, reviews: 85, description: "Charming boutique Italian market on Marconi Ave featuring artisanal espresso, imported Italian goods, charcuterie boards, and curated local products from The Hill neighborhood.", tags: ["Italian Market", "Boutique", "The Hill"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Marconi+Mercato+St+Louis", lat: 38.6162, lng: -90.2775 },

  // --- WEST COUNTY & MANCHESTER ADDITIONS ---
  { id: "wc1", name: "The Ground Coffeehouse & Plant Shop", area: "Ballwin", address: "109 Ballpark Dr, Ballwin, MO 63011", rating: 4.8, reviews: 141, description: "Woman-owned Ballwin gem pairing locally sourced craft coffee, lattes, and pastries with a curated houseplant shop downstairs. A warm, green community gathering spot.", tags: ["Plants", "Local", "Woman-owned"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.thegroundstl.com/", googleMapsUrl: "https://maps.google.com/?q=The+Ground+Coffeehouse+Plant+Shop+Ballwin", lat: 38.5951, lng: -90.5462 },
  { id: "wc2", name: "Qahwatea Coffee", area: "Ellisville", address: "15957 Manchester Rd, Ellisville, MO 63011", rating: 4.8, reviews: 437, description: "Family-run Yemeni coffee house in Ellisville serving traditional Yemeni coffee, pistachio lattes, cardamom chai, and authentic Middle Eastern desserts like baklava and kunafa. Open late.", tags: ["Yemeni", "Late Night", "Desserts"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Qahwatea+Coffee+Ellisville", lat: 38.5926, lng: -90.5738 },
  { id: "wc3", name: "7 Brew Coffee", area: "Ellisville", address: "15444-A Manchester Rd, Ellisville, MO 63011", rating: 3.8, reviews: 27, description: "Fast, friendly drive-thru coffee chain in Ellisville serving espresso, flavored lattes, smoothies, Italian sodas, and energy drinks. Convenient for Manchester Rd commuters.", tags: ["Drive-Thru", "Quick Service", "Affordable"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://7brew.com/menu", googleMapsUrl: "https://maps.google.com/?q=7+Brew+Coffee+Ellisville", lat: 38.5932, lng: -90.5685 },
  { id: "wc4", name: "Rosemary Coffee Co", area: "Manchester", address: "1316 Big Bend Rd, Manchester, MO 63021", rating: 4.9, reviews: 121, description: "Earthy, plant-filled Manchester cafe with specialty espresso, matcha lattes, seasonal drinks, and house-baked goods. Their motto: Be Kind. Stay Weird. Drink Coffee.", tags: ["Earthy", "Cozy", "Specialty"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.rosemarycoffeeco.com/", googleMapsUrl: "https://maps.google.com/?q=Rosemary+Coffee+Co+Manchester+MO", lat: 38.5805, lng: -90.5065 },
  { id: "wc5", name: "Tous les Jours Bakery Cafe", area: "Ballwin", address: "14248 Manchester Rd, Suite D, Ballwin, MO 63011", rating: 4.1, reviews: 89, description: "French-Asian fusion bakery in Ballwin serving freshly baked artisan breads, cream-filled pastries, layered cakes, and specialty coffee and tea drinks daily.", tags: ["French-Asian", "Bakery", "Pastries"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://tljus.com/stores/manchester-14248-manchester-rd-suite-d", googleMapsUrl: "https://maps.google.com/?q=Tous+les+Jours+Ballwin+MO", lat: 38.5935, lng: -90.5545 },
  { id: "wc6", name: "Six North Cafe", area: "Ballwin", address: "14438 Clayton Rd, Ballwin, MO 63011", rating: 4.3, reviews: 336, description: "Warm, family-owned Ballwin cafe serving Kaldi's house-roasted coffee alongside hand-crafted breakfast sandwiches, paninis, homemade soups, and fresh-baked pastries.", tags: ["Kaldi's Coffee", "Breakfast", "Family-owned"], image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=2070&auto=format&fit=crop", menuUrl: "https://6northcafe.com/", googleMapsUrl: "https://maps.google.com/?q=6+North+Cafe+Ballwin", lat: 38.5958, lng: -90.5395 },
  { id: "wc7", name: "More Than Coffee", area: "Manchester", address: "14240 Manchester Rd, Manchester, MO 63011", rating: 4.8, reviews: 179, description: "Inspiring Manchester cafe training and employing individuals with disabilities. Serves quality espresso, specialty lattes, smoothies, and fresh-baked goods. Great coffee for a great cause.", tags: ["Social Good", "Mission-driven", "Community"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://morethancoffee.net/", googleMapsUrl: "https://maps.google.com/?q=More+Than+Coffee+Manchester+MO", lat: 38.5935, lng: -90.5505 },
  { id: "wc8", name: "Honey Bee Tea", area: "Manchester", address: "429 Lafayette Center Dr, Manchester, MO 63011", rating: 4.8, reviews: 975, description: "Premium Manchester boba tea shop using organic ingredients imported from Taiwan. Famous for their Okinawa Milk Tea, ube taro latte, Vietnamese coffee, and fruit teas.", tags: ["Boba Tea", "Vietnamese Coffee", "Organic"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://honeybt.com/", googleMapsUrl: "https://maps.google.com/?q=Honey+Bee+Tea+Manchester+MO", lat: 38.5862, lng: -90.5148 },
  { id: "wc9", name: "Lucky Dog Central", area: "Wildwood", address: "16917 Manchester Rd, Wildwood, MO 63040", rating: 4.9, reviews: 179, description: "Unique Wildwood cafe where dogs play off-leash in a fenced yard while owners enjoy craft espresso, cold brew, hearty sandwiches, and baked treats. Pupcakes available for furry friends.", tags: ["Dog Friendly", "Pet Cafe", "Craft Coffee"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.luckydogcentral.com/", googleMapsUrl: "https://maps.google.com/?q=Lucky+Dog+Central+Wildwood+MO", lat: 38.5795, lng: -90.6425 },
  { id: "wc10", name: "UKRAFT Brunch Cafe", area: "Chesterfield", address: "14888 Clayton Rd, Chesterfield, MO 63017", rating: 4.8, reviews: 575, description: "Popular Chesterfield brunch cafe serving hand-crafted cold brew, acai bowls, avocado toast, smoothies, and creative egg dishes with gluten-free and vegan options throughout.", tags: ["Brunch", "Gluten-free", "Vegan Options"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://ukraftbrunchcafe.com/", googleMapsUrl: "https://maps.google.com/?q=UKRAFT+Brunch+Cafe+Chesterfield", lat: 38.6322, lng: -90.5285 },

  // --- NORTH COUNTY, ST. ANN, MARYLAND HEIGHTS, OVERLAND & ST. CHARLES ADDITIONS ---
  { id: "nc1", name: "The Garden Studio Cafe", area: "Ferguson", address: "100 N Florissant Rd, Ferguson, MO 63135", rating: 4.9, reviews: 45, description: "Community-driven Ferguson cafe doubling as an art gallery and transformation center. Serves specialty coffee flights, espresso with housemade syrups, and pastries in an inspiring space.", tags: ["Community", "Art Gallery", "Coffee Flights"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.thegardenstudio.cafe/", googleMapsUrl: "https://maps.google.com/?q=The+Garden+Studio+Cafe+Ferguson", lat: 38.7445, lng: -90.3048 },
  { id: "nc2", name: "Christine's Coffee", area: "South City", address: "8406 Natural Bridge Rd, St. Louis, MO 63121", rating: 4.6, reviews: 104, description: "Welcoming, woman-owned cafe on Natural Bridge serving espresso, flavored lattes, hearty omelets, and pastries. Known for fun theme nights, trivia, and a dog-friendly patio.", tags: ["Woman-owned", "Theme Nights", "Dog Friendly"], image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=2070&auto=format&fit=crop", menuUrl: "https://christinescoffee.getbento.com/online-ordering/", googleMapsUrl: "https://maps.google.com/?q=Christine's+Coffee+St+Louis", lat: 38.6945, lng: -90.2885 },
  { id: "nc3", name: "Koffee Ko", area: "South City", address: "1280 Saint Cyr Rd, St. Louis, MO 63137", rating: 4.8, reviews: 116, description: "Black-owned artisan coffee shop serving high-quality espresso, creative brunch dishes, and unique spiked coffee cocktails. A vibrant, welcoming North County destination.", tags: ["Black-owned", "Artisan", "Brunch"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.thekoffeeko.com/", googleMapsUrl: "https://maps.google.com/?q=Koffee+Ko+St+Louis", lat: 38.7265, lng: -90.2535 },
  { id: "nc4", name: "Brew & Bites Cafe", area: "St. Ann", address: "3191 Ashby Rd, Suite 2, St. Ann, MO 63074", rating: 4.8, reviews: 217, description: "Creative Mexican-American fusion cafe in St. Ann serving candy-inspired specialty lattes (mazapan, Lucas), breakfast tacos, chilaquiles, and coffee flights. Pet-friendly patio.", tags: ["Mexican-American", "Fusion", "Pet Friendly"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://brew-and-bites-cafe2024.square.site/", googleMapsUrl: "https://maps.google.com/?q=Brew+Bites+Cafe+St+Ann", lat: 38.7275, lng: -90.3885 },
  { id: "nc5", name: "The Foundry Bakery", area: "Maryland Heights", address: "11424 Dorsett Rd, Maryland Heights, MO 63043", rating: 4.8, reviews: 576, description: "Artisan Taiwanese-inspired bakery in Maryland Heights serving beautifully crafted pineapple cakes, egg tarts, boba drinks, matcha lattes, and espresso in an elegant setting.", tags: ["Taiwanese", "Bakery", "Boba"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.thefoundrybakery.com/", googleMapsUrl: "https://maps.google.com/?q=The+Foundry+Bakery+Maryland+Heights", lat: 38.7105, lng: -90.4535 },
  { id: "nc6", name: "LaJoy's Coffee Cafe", area: "Overland", address: "8909 Lackland Rd, Overland, MO 63114", rating: 4.6, reviews: 185, description: "Black-owned Overland cafe serving made-to-order omelets, waffles, turkey burgers, and top-notch espresso in a sunny, relaxed space on Lackland Rd. A neighborhood gem.", tags: ["Breakfast", "Black-owned", "Relaxed"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.lajoyscoffeecafe.com/menu", googleMapsUrl: "https://maps.google.com/?q=LaJoy's+Coffee+Cafe+Overland", lat: 38.6975, lng: -90.3685 },
  { id: "nc7", name: "The Sweet Spot Cafe", area: "Florissant", address: "2575 N Highway 67, Florissant, MO 63033", rating: 4.7, reviews: 58, description: "Cheerful, family-run Florissant cafe serving fresh donuts, hearty breakfast platters, espresso drinks, milkshakes, and ice cream. A sweet neighborhood favorite off Highway 67.", tags: ["Donuts", "Breakfast", "Family-run"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://sweetspotcafe.com/", googleMapsUrl: "https://maps.google.com/?q=The+Sweet+Spot+Cafe+Florissant", lat: 38.7925, lng: -90.3225 },
  { id: "nc8", name: "Higher Groundz Coffee & Tea", area: "Maryland Heights", address: "12075 Dorsett Rd, Maryland Heights, MO 63043", rating: 5.0, reviews: 279, description: "Perfect 5-star rated Maryland Heights cafe with exceptionally friendly service, quality espresso, specialty teas, and a warm, faith-based community atmosphere on Dorsett Rd.", tags: ["5-Star", "Community", "Tea"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://zionmh.org/hgz", googleMapsUrl: "https://maps.google.com/?q=Higher+Groundz+Coffee+Tea+Maryland+Heights", lat: 38.7085, lng: -90.4385 },
  { id: "nc9", name: "Mocha Point Yemeni Coffee Co.", area: "St. Charles", address: "343 N Main St, St. Charles, MO 63301", rating: 4.9, reviews: 535, description: "Family-owned Yemeni coffee house on historic Main Street serving authentic Yemeni coffee, pistachio lattes, baklava, and traditional pastries. Open late with a warm, inviting atmosphere.", tags: ["Yemeni", "Late Night", "Pastries"], image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://mochapointcoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Mocha+Point+Yemeni+Coffee+St+Charles", lat: 38.7875, lng: -90.4815 },
  { id: "nc10", name: "La Belle Vie", area: "St. Charles", address: "1200 N 2nd St, St. Charles, MO 63301", rating: 4.7, reviews: 935, description: "Charming French-inspired cafe in historic Frenchtown serving sweet and savory crepes, espresso, pastries, wine, and sandwiches. Steps from the Katy Trail in St. Charles.", tags: ["French", "Crepes", "Frenchtown"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://labelleviefrenchtown.com/", googleMapsUrl: "https://maps.google.com/?q=La+Belle+Vie+Frenchtown+St+Charles", lat: 38.7925, lng: -90.4795 },
  { id: "nc11", name: "Picasso's Coffee", area: "St. Charles", address: "101 N Main St, St. Charles, MO 63301", rating: 4.7, reviews: 1400, description: "Beloved St. Charles Main Street institution serving micro-roasted coffee, espresso, hearty breakfast, lunch, wine, and craft beer with stunning Missouri River views from the patio.", tags: ["Main Street", "Micro-roasted", "River Views"], image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=2070&auto=format&fit=crop", menuUrl: "https://www.picassoscoffeehouse.com/", googleMapsUrl: "https://maps.google.com/?q=Picasso's+Coffee+St+Charles", lat: 38.7855, lng: -90.4815 },

  // --- ST. CHARLES COUNTY & SURROUNDING ADDITIONS ---
  { id: "sc1b", name: "Saint Charles Coffee & Creperie", area: "St. Charles", address: "336 S Main St, St. Charles, MO 63301", rating: 4.5, reviews: 96, description: "Delightful cafe on Historic Main Street serving sweet and savory crepes, quality espresso, lattes, and fresh pastries in a charming, old-town St. Charles atmosphere.", tags: ["Crepes", "Main Street", "Pastries"], image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.stcharlescoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Saint+Charles+Coffee+Creperie", lat: 38.7835, lng: -90.4825 },
  { id: "sc2", name: "Common Grounds Coffee House", area: "Winfield", address: "205 Main St, Winfield, MO 63389", rating: 4.8, reviews: 92, description: "Charming small-town gem on Winfield's Main Street serving expertly brewed coffee, espresso, seasonal lattes, and fresh pastries. A warm retreat with friendly regulars and cozy vibes.", tags: ["Small Town", "Cozy", "Main Street"], image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Common+Grounds+Coffee+House+Winfield+MO", lat: 38.9975, lng: -90.7385 },
  { id: "sc3", name: "Southern Grace Coffee", area: "Lake St Louis", address: "20 Meadows Circle Dr, Suite 216, Lake St Louis, MO 63367", rating: 4.7, reviews: 147, description: "Adorable Lake St. Louis cafe at The Meadows serving specialty lattes, cold brew, hearty breakfast sandwiches, and house-baked muffins with warm, Southern-inspired hospitality.", tags: ["Specialty", "Breakfast", "Meadows"], image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://southerngracecoffee.com/", googleMapsUrl: "https://maps.google.com/?q=Southern+Grace+Coffee+Lake+St+Louis", lat: 38.7785, lng: -90.7855 },
  { id: "sc4", name: "Pink Willow Cafe", area: "Cottleville", address: "5523 Oak St, Cottleville, MO 63304", rating: 4.0, reviews: 273, description: "Instagram-worthy Cottleville brunch cafe with charming pink decor, Messenger Coffee espresso, avocado toast, mimosa flights, and a stunning hand-painted willow tree mural.", tags: ["Brunch", "Pink Decor", "Mimosas"], image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://pinkwillowcafe.com/", googleMapsUrl: "https://maps.google.com/?q=Pink+Willow+Cafe+Cottleville", lat: 38.7465, lng: -90.6545 },
  { id: "sc5", name: "Upshot Coffee Brake Shop", area: "St. Charles", address: "816 N Kingshighway St, St. Charles, MO 63301", rating: 4.6, reviews: 329, description: "Specialty coffee roaster housed in a beautifully preserved 1950s gas station near Lindenwood University. Serves house-roasted espresso, pour-overs, and pastries with unique retro vibes.", tags: ["Roaster", "Retro", "Unique Venue"], image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://weareupshotcoffee.com/pages/brakeshop", googleMapsUrl: "https://maps.google.com/?q=Upshot+Coffee+Brake+Shop+St+Charles", lat: 38.7925, lng: -90.4925 },
  { id: "sc6", name: "Flower Coffee Collective", area: "Wentzville", address: "5020 Hwy P, Wentzville, MO 63385", rating: 5.0, reviews: 118, description: "Perfect 5-star hidden gem in Wentzville — a charming coffee camper with a drive-thru, outdoor picnic seating, craft espresso, seasonal lattes, and the friendliest baristas around.", tags: ["Drive-Thru", "Hidden Gem", "Craft Coffee"], image: "https://images.unsplash.com/photo-1469631423273-6995642f6a40?q=80&w=2071&auto=format&fit=crop", menuUrl: "#", googleMapsUrl: "https://maps.google.com/?q=Flower+Coffee+Collective+Wentzville", lat: 38.7985, lng: -90.8525 },
  { id: "sc7", name: "Grounded and Free", area: "St. Charles", address: "519 S 5th St, St. Charles, MO 63301", rating: 5.0, reviews: 85, description: "Perfect 5-star boho-themed boutique in St. Charles combining specialty espresso drinks, matcha, and pastries with ethically sourced clothing and a cozy upstairs lounge for relaxing.", tags: ["Boho", "Boutique", "Lounge"], image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2071&auto=format&fit=crop", menuUrl: "https://www.wearegroundedandfree.com/", googleMapsUrl: "https://maps.google.com/?q=Grounded+and+Free+St+Charles", lat: 38.7815, lng: -90.4795 },
];
