// Uses the same Places API v1 pattern as your existing working functions
// Replace netlify/functions/geocode-all.mjs with this, deploy, then visit:
// https://magnificent-brioche-ecb9bd.netlify.app/api/geocode-all

const shops = [
  { id: "1", name: "Sump Coffee", address: "3700 S Jefferson Ave, St. Louis, MO 63118" },
  { id: "2", name: "Blueprint Coffee", address: "6225 Delmar Blvd, St. Louis, MO 63130" },
  { id: "3", name: "Comet Coffee", address: "5708 Oakland Ave, St. Louis, MO 63110" },
  { id: "4", name: "Teleo Coffee", address: "132 W Monroe Ave, Kirkwood, MO 63122" },
  { id: "5", name: "Antagonist Cafe", address: "2727 S 12th St, St. Louis, MO 63118" },
  { id: "6", name: "Protagonist Cafe", address: "1700 S 9th St, St. Louis, MO 63104" },
  { id: "7", name: "23 West Coffee", address: "23 W Lockwood Ave, Webster Groves, MO 63119" },
  { id: "8", name: "Maypop Coffee", address: "803 Marshall Ave, Webster Groves, MO 63119" },
  { id: "9", name: "Looking Meadow Cafe", address: "2500 Sutton Blvd, Maplewood, MO 63143" },
  { id: "11", name: "Northwest Coffee", address: "4251 Laclede Ave, St. Louis, MO 63108" },
  { id: "13", name: "Coma Coffee", address: "1034 S Brentwood Blvd, Richmond Heights, MO 63117" },
  { id: "14", name: "The Drip", address: "3615 Potomac St, St. Louis, MO 63116" },
  { id: "15", name: "Hartford Coffee", address: "3974 Hartford St, St. Louis, MO 63116" },
  { id: "16", name: "SweetArt", address: "3701 Lindell Blvd, St. Louis, MO 63108" },
  { id: "17", name: "La Finca Coffee", address: "104 S Central Ave, Eureka, MO 63025" },
  { id: "20", name: "Pioneer Bakery", address: "210 N Kirkwood Rd, Kirkwood, MO 63122" },
  { id: "24", name: "Deer Creek Coffee", address: "9820 Clayton Rd, Ladue, MO 63124" },
  { id: "25", name: "Exit 11 Coffee", address: "2944 S Brentwood Blvd, Brentwood, MO 63144" },
  { id: "27", name: "Latte Lounge", address: "2190 N Waterford Dr, Florissant, MO 63033" },
  { id: "30", name: "CoffeeStamp", address: "2511 S Jefferson Ave, St. Louis, MO 63104" },
  { id: "31", name: "Living Room Coffee", address: "2810 Sutton Blvd, Maplewood, MO 63143" },
  { id: "32", name: "Cafe Osage", address: "3504 Caroline St, St. Louis, MO 63104" },
  { id: "34", name: "Soulard Coffee Garden", address: "1901 Withnell Ave, St. Louis, MO 63118" },
  { id: "35", name: "Kayak Coffee", address: "6269 Delmar Blvd, St. Louis, MO 63130" },
  { id: "36", name: "Park Avenue Coffee Shaw", address: "5147 Shaw Ave, St. Louis, MO 63110" },
  { id: "37", name: "Songbird Coffee", address: "3606 Arsenal St, St. Louis, MO 63116" },
  { id: "38", name: "Foundation Grounds", address: "7298 Manchester Rd, Maplewood, MO 63143" },
  { id: "39", name: "Cafe Boogaloo", address: "2 E 5th St, Washington, MO 63090" },
  { id: "40", name: "Kaldi's Big Bend", address: "8122 Big Bend Blvd, Webster Groves, MO 63119" },
  { id: "41", name: "Fozzie's Sandwich Emporium", address: "701 S Riverside Dr, St. Charles, MO 63301" },
  { id: "43", name: "Crema Coffeehouse", address: "4066 Russell Blvd, St. Louis, MO 63110" },
  { id: "45", name: "222 Artisan Bakery St Charles", address: "1218 N 2nd St, St. Charles, MO 63301" },
  { id: "k1", name: "Kaldi's DeMun", address: "700 DeMun Ave, St. Louis, MO 63105" },
  { id: "k2", name: "Kaldi's Skinker", address: "270 N Skinker Blvd, St. Louis, MO 63130" },
  { id: "k3", name: "Kaldi's Kirkwood", address: "120 S Kirkwood Rd, Kirkwood, MO 63122" },
  { id: "k4", name: "Kaldi's Euclid", address: "52 N Euclid Ave, St. Louis, MO 63108" },
  { id: "k5", name: "Kaldi's Chesterfield", address: "17211 Chesterfield Airport Rd, Chesterfield, MO 63005" },
  { id: "k7", name: "Kaldi's Cortex", address: "4590 Children's Place, Saint Louis, MO 63110" },
  { id: "k8", name: "Kaldi's S Euclid", address: "520 S Euclid Ave, St. Louis, MO 63108" },
  { id: "a1", name: "Coffee Culture", address: "5532 S Lindbergh Blvd, St. Louis, MO 63123" },
  { id: "b1", name: "Ballwin Coffee", address: "15480 Clayton Rd, Ballwin, MO 63011" },
  { id: "bp1", name: "Park Avenue Coffee Cherokee", address: "1926 Cherokee St, St. Louis, MO 63118" },
  { id: "bp2", name: "Cafe Ventana", address: "2101 Cherokee St, St. Louis, MO 63118" },
  { id: "ca1", name: "Holly Hills Coffee", address: "527 Holly Hills Ave, St. Louis, MO 63111" },
  { id: "ca2", name: "Macklind Coffee", address: "5838 Macklind Ave, St. Louis, MO 63109" },
  { id: "cl1", name: "Clayton Coffee", address: "120 S Central Ave, Clayton, MO 63105" },
  { id: "cl2", name: "Poulton Coffee", address: "36 N Brentwood Blvd, Clayton, MO 63105" },
  { id: "cl3", name: "Meramec Coffee", address: "14 N Meramec Ave, Clayton, MO 63105" },
  { id: "cc1", name: "Gateway Coffee Company", address: "12806 Olive Blvd, St. Louis, MO 63141" },
  { id: "cc2", name: "The Ground Coffee", address: "109 Ballpark Dr, Ballwin, MO 63011" },
  { id: "cc3", name: "Revocup Coffee", address: "9200 Olive Blvd, Olivette, MO 63132" },
  { id: "dt1", name: "Crema Coffeehouse Dogtown", address: "275 Union Blvd, St. Louis, MO 63108" },
  { id: "f1", name: "Hive Cafe Ferguson", address: "235 S Florissant Rd, Ferguson, MO 63135" },
  { id: "ls1", name: "E61 Cafe", address: "307 Belt Ave, St. Louis, MO 63112" },
  { id: "m1", name: "Mauhaus Cat Cafe", address: "3101 Sutton Blvd, Maplewood, MO 63143" },
  { id: "sc1", name: "Upshot Coffee", address: "3153 Morgan Ford Rd, St. Louis, MO 63116" },
  { id: "uc1", name: "Zensia", address: "8121 Maryland Ave, St. Louis, MO 63105" },
  { id: "csv2", name: "High Ridge Coffee", address: "3015 High Ridge Blvd, High Ridge, MO 63049" },
  { id: "csv5", name: "Euclid Coffee", address: "399 N Euclid Ave, St. Louis, MO 63108" },
  { id: "csv6", name: "Forsyth Coffee", address: "7337 Forsyth Blvd, Clayton, MO 63105" },
  { id: "csv8", name: "Germania Coffee Clayton", address: "8027 Forsyth Blvd, Clayton, MO 63105" },
  { id: "csv9", name: "The Press Cafe", address: "725 Kingsland Ave, University City, MO 63130" },
  { id: "csv10", name: "Ethio Coffee", address: "12670 Dorsett Rd, Maryland Heights, MO 63043" },
  { id: "csv11", name: "Olive Coffee", address: "12344 Olive Blvd, Creve Coeur, MO 63141" },
  { id: "csv13", name: "4th Street Coffee", address: "442 N 4th St, St. Louis, MO 63102" },
  { id: "csv14", name: "Broadway Coffee", address: "211 N Broadway, St. Louis, MO 63102" },
  { id: "csv15", name: "Manchester Coffee Kirkwood", address: "10907 Manchester Rd, Kirkwood, MO 63122" },
  { id: "csv16", name: "Jefferson Coffee Kirkwood", address: "151 W Jefferson Ave, Kirkwood, MO 63122" },
  { id: "csv17", name: "Park Ave Coffee", address: "1919 Park Ave, St. Louis, MO 63104" },
  { id: "csv18", name: "Sutton Coffee Maplewood", address: "2500 Sutton Ave, Maplewood, MO 63143" },
  { id: "csv20", name: "Washington Ave Coffee", address: "2647 Washington Ave, St. Louis, MO 63103" },
  { id: "csv26", name: "Lockwood Coffee Webster", address: "100 W Lockwood Ave, Webster Groves, MO 63119" },
  { id: "h1", name: "Cafe Dolce", address: "5143 Daggett Ave, St. Louis, MO 63110" },
  { id: "h2", name: "Park Avenue Coffee Hill", address: "5105 Columbia Ave, St. Louis, MO 63139" },
  { id: "h3", name: "MountainHouse Cafe", address: "2901 Macklind Ave, St. Louis, MO 63139" },
  { id: "h4", name: "Marconi Coffee", address: "2030 Marconi Ave, St. Louis, MO 63110" },
  { id: "wc1", name: "Whisk Coffee Ballwin", address: "109 Ballpark Dr, Ballwin, MO 63011" },
  { id: "wc2", name: "Whisk Coffee Ellisville", address: "15957 Manchester Rd, Ellisville, MO 63011" },
  { id: "wc4", name: "Whisk Coffee Manchester", address: "1316 Big Bend Rd, Manchester, MO 63021" },
  { id: "wc5", name: "Whisk Coffee Ballwin 2", address: "14248 Manchester Rd, Ballwin, MO 63011" },
  { id: "wc6", name: "Whisk Coffee Clayton Rd", address: "14438 Clayton Rd, Ballwin, MO 63011" },
  { id: "wc7", name: "Whisk Coffee Manchester 2", address: "14240 Manchester Rd, Manchester, MO 63011" },
  { id: "wc9", name: "Whisk Coffee Wildwood", address: "16917 Manchester Rd, Wildwood, MO 63040" },
  { id: "wc10", name: "Whisk Coffee Chesterfield", address: "14888 Clayton Rd, Chesterfield, MO 63017" },
  { id: "nc1", name: "Garden Studio Cafe", address: "100 N Florissant Rd, Ferguson, MO 63135" },
  { id: "nc2", name: "Natural Bridge Coffee", address: "8406 Natural Bridge Rd, St. Louis, MO 63121" },
  { id: "nc3", name: "Koffee Ko", address: "1280 Saint Cyr Rd, St. Louis, MO 63137" },
  { id: "nc4", name: "St Ann Coffee", address: "3191 Ashby Rd, St. Ann, MO 63074" },
  { id: "nc5", name: "Dorsett Coffee", address: "11424 Dorsett Rd, Maryland Heights, MO 63043" },
  { id: "nc6", name: "LaJoys Coffee", address: "8909 Lackland Rd, Overland, MO 63114" },
  { id: "nc8", name: "Dorsett Coffee 2", address: "12075 Dorsett Rd, Maryland Heights, MO 63043" },
  { id: "nc9", name: "Main St Charles Coffee", address: "343 N Main St, St. Charles, MO 63301" },
  { id: "nc10", name: "2nd St Coffee", address: "1200 N 2nd St, St. Charles, MO 63301" },
  { id: "nc11", name: "101 Main Coffee", address: "101 N Main St, St. Charles, MO 63301" },
  { id: "sc1b", name: "S Main Coffee", address: "336 S Main St, St. Charles, MO 63301" },
  { id: "sc2", name: "Winfield Coffee", address: "205 Main St, Winfield, MO 63389" },
  { id: "sc3", name: "Lake St Louis Coffee", address: "20 Meadows Circle Dr, Lake St Louis, MO 63367" },
  { id: "sc4", name: "Cottleville Coffee", address: "5523 Oak St, Cottleville, MO 63304" },
  { id: "sc5", name: "Kingshighway Coffee", address: "816 N Kingshighway St, St. Charles, MO 63301" },
  { id: "sc6", name: "Wentzville Coffee", address: "5020 Hwy P, Wentzville, MO 63385" },
  { id: "sc7", name: "5th St Coffee", address: "519 S 5th St, St. Charles, MO 63301" },
  { id: "s_goshen", name: "Goshen Coffee Soulard", address: "910 Geyer Ave, St. Louis, MO 63104" },
  { id: "s_cafemiami", name: "Cafe Miami", address: "2022 S 12th St, St. Louis, MO 63104" },
  { id: "bp_goodstrangers", name: "Good Strangers Coffee", address: "2614 Cherokee St, St. Louis, MO 63118" },
  { id: "bp_bentoncafe", name: "Benton Park Cafe", address: "2901 Salena St, St. Louis, MO 63118" },
  { id: "bp_cobblestone", name: "Cobblestone STL", address: "701 N 1st St, St. Louis, MO 63102" },
  { id: "mt_shortwave", name: "Shortwave Coffee", address: "33 N Sarah St, St. Louis, MO 63108" },
  { id: "mt_noteworthy", name: "Noteworthy Coffee", address: "504 N Newstead Ave, St. Louis, MO 63108" },
  { id: "on_dailydrip", name: "Daily Drip", address: "2804 N 14th St, St. Louis, MO 63107" },
  { id: "cwe_bowood", name: "Bowood Farms", address: "4605 Olive St, St. Louis, MO 63108" },
  { id: "dt_goodpress", name: "Good Press Coffee", address: "1528 Locust St, St. Louis, MO 63103" },
  { id: "dt_bp_wash", name: "Blueprint Washington Ave", address: "3301 Washington Ave, St. Louis, MO 63103" },
  { id: "dt_pac_olive", name: "Park Avenue Coffee Olive", address: "521 Olive St, St. Louis, MO 63101" },
  { id: "tg_wellmet", name: "Well Met Coffee", address: "4100 Shenandoah Ave, St. Louis, MO 63116" },
  { id: "tg_sacredgrounds", name: "Sacred Grounds Edwardsville", address: "233 N Main St, Edwardsville, IL 62025" },
  { id: "tg_sugarhi", name: "Sugar High Belleville", address: "100 E Main St, Belleville, IL 62221" },
  { id: "tg_hache", name: "Hache Herbal", address: "6350 S Rosebury Ave, St. Louis, MO 63105" },
  { id: "sc_passevent", name: "Pass the Past Coffee", address: "4740 McPherson Ave, St. Louis, MO 63108" },
  { id: "sc_coffeegirl", name: "Coffee Girl Waterloo", address: "219 S Main St, Waterloo, IL 62298" },
  { id: "sc_bp_watson", name: "Blueprint Watson", address: "4206 Watson Rd, St. Louis, MO 63109" },
  { id: "mt_pac_cortex", name: "Park Avenue Coffee Cortex", address: "4220 Duncan Ave, St. Louis, MO 63110" },
  { id: "sh_comet_shaw", name: "Comet Coffee Shaw", address: "4474 Shaw Blvd, St. Louis, MO 63110" },
  { id: "kaldis_ellisv", name: "Kaldi's Ellisville", address: "147 Clarkson Road, Ellisville, MO 63011" },
  { id: "kaldis_ladue", name: "Kaldi's Ladue", address: "9214 Clayton Rd, St. Louis, MO 63124" },
  { id: "kaldis_crescent", name: "Kaldi's Crescent", address: "187 Carondelet Plaza, Clayton, MO 63105" },
  { id: "upshot_flyby", name: "Upshot Flyby", address: "3172 Morgan Ford Rd, St. Louis, MO 63116" },
  { id: "upshot_hifi", name: "Upshot HiFi", address: "8401 Maryland Ave, Clayton, MO 63105" },
  { id: "wg_cafeabbey", name: "Cafe on the Abbey Columbia IL", address: "322 S Main St, Columbia, IL 62236" },
  { id: "wg_oatshoney", name: "Oats and Honey Creve Coeur", address: "624 N New Ballas Rd, Creve Coeur, MO 63141" },
  { id: "wg_cove", name: "Cove Cafe", address: "6060 Telegraph Rd, St. Louis, MO 63129" },
  { id: "kw_nathanielreid", name: "Nathaniel Reid Bakery", address: "11243 Manchester Rd, Kirkwood, MO 63122" },
  { id: "kw_crookedtree", name: "Crooked Tree St Charles", address: "559 1st Capitol Dr, St. Charles, MO 63301" },
  { id: "kw_littlesloft", name: "Littles Loft Kirkwood", address: "117 W Argonne Dr, Kirkwood, MO 63122" },
  { id: "cl_half", name: "Half and Half Clayton", address: "8135 Maryland Ave, Clayton, MO 63105" },
  { id: "cl_madebylia", name: "Made by Lia Florissant", address: "610 Rue St. Francois St, Florissant, MO 63031" },
  { id: "cl_justitia", name: "Justitia Coffeehouse Belleville", address: "18 E Main St, Belleville, IL 62220" },
  { id: "ld_russells", name: "Russells Cafe Fenton", address: "952 Brookwood Center, Fenton, MO 63026" },
  { id: "ss_russellsmac", name: "Russells on Macklind", address: "5400 Murdoch Ave, St. Louis, MO 63109" },
  { id: "uc_winslows2", name: "Winslows Home", address: "7213 Delmar Blvd, University City, MO 63130" },
  { id: "uc_ome", name: "Ome Cafe", address: "6600 Delmar Blvd, University City, MO 63130" },
  { id: "uc_cafefer", name: "Cafe Fermata Chesterfield", address: "16626 Old Chesterfield Rd, Chesterfield, MO 63017" },
  { id: "mw_provingground", name: "Proving Ground Coffee Columbia IL", address: "180 Columbia Centre Dr, Columbia, IL 62236" },
  { id: "mw_lacosecha", name: "La Cosecha", address: "7360 Manchester Rd, Maplewood, MO 63143" },
  { id: "mw_brewsbikes", name: "Brews Cafe Chesterfield", address: "17089 N Outer 40 Rd, Chesterfield, MO 63005" },
  { id: "mw_tiltedheads", name: "Tilted Heads", address: "2961 Dougherty Ferry Rd, St. Louis, MO 63122" },
  { id: "fg_bridge", name: "Bridge Coffee House St Charles", address: "3257 Domain St, St. Charles, MO 63301" },
  { id: "fg_longstory", name: "LongStory Coffee Belleville", address: "732 S Illinois St, Belleville, IL 62220" },
  { id: "stc_post", name: "Post Commons Alton IL", address: "300 Alby St, Alton, IL 62002" },
  { id: "stc_222", name: "222 Artisan Bakery Edwardsville", address: "222 St Louis St, Edwardsville, IL 62025" },
  { id: "stc_qahwatime", name: "Qahwa Time", address: "5469 Baumgartner Road, St. Louis, MO 63129" },
  { id: "stc_pour", name: "Pour 322 Belleville", address: "322 E Main St, Belleville, IL 62220" },
  { id: "cc_maeva", name: "Maevas Coffee Alton", address: "1320 Milton Rd, Alton, IL 62002" },
  { id: "ch_sweetwaters", name: "Sweetwaters Coffee The Hill", address: "4071 Chouteau Ave, St. Louis, MO 63110" },
  { id: "ch_lemacar", name: "Le Macaron Webster Groves", address: "111 W Lockwood Ave, Webster Groves, MO 63119" },
  { id: "ch_gloriajs", name: "Gloria Jeans Fairview Heights", address: "134 St Clair Square, Fairview Heights, IL 62208" },
  { id: "bw_espressoyourself", name: "Espresso Yourself Southampton", address: "5351 Devonshire Ave, St. Louis, MO 63109" },
  { id: "mc_verona", name: "Verona Coffee Collinsville", address: "101 E Main St, Collinsville, IL 62234" },
  { id: "mc_twpikes", name: "Twin Pikes High Ridge", address: "2528 Gravois Rd, High Ridge, MO 63049" },
  { id: "il_goshen_edw", name: "Goshen Coffee Edwardsville", address: "6120 Shoger Dr, Edwardsville, IL 62025" },
  { id: "il_goshen_gc", name: "Goshen Coffee Glen Carbon", address: "1 Junction Dr, Glen Carbon, IL 62034" },
  { id: "il_germania_alton", name: "Germania Coffee Alton", address: "211 Ridge St, Alton, IL 62002" },
  { id: "il_germania_ealton", name: "Germania Coffee East Alton", address: "Eastgate Plaza, East Alton, IL 62024" },
  { id: "ww_frontier", name: "Frontier Perk St Charles", address: "108 S Main St, St. Charles, MO 63301" },
  { id: "fl_memes", name: "Memes Coffee Granite City", address: "1529 Johnson Rd, Granite City, IL 62040" },
  { id: "bv_cafefleur", name: "Cafe Fleur", address: "5569 Telegraph Rd, Saint Louis, MO 63129" },
  { id: "dt_trust", name: "Trust Coffee", address: "401 Pine St, St. Louis, MO 63102" },
  { id: "dp_dailybread", name: "Daily Bread Bakery", address: "11719 Manchester Rd, St. Louis, MO 63131" },
  { id: "latte_lounge2", name: "Latte Lounge CWE", address: "3131 Olive St, St. Louis, MO 63103" },
  { id: "kentzo_ofallon", name: "Kentzo Koffee OFallon", address: "111 N Main St, O'Fallon, MO 63366" },
  { id: "ek_orangecouch", name: "Orange Couch Coffee Eureka", address: "98 The Legends Parkway, Eureka, MO 63025" },
  { id: "ek_sarahscentral", name: "Sarahs on Central Eureka", address: "127 S Central Ave, Eureka, MO 63025" },
  { id: "gl_glendagrind", name: "Glendale Grind", address: "421 N Sappington Rd, Glendale, MO 63122" },
  { id: "wg_telva", name: "Telva at the Ridge", address: "60 N Gore Ave, Webster Groves, MO 63119" },
];

async function geocode(name, address, apiKey) {
  const res = await fetch("https://places.googleapis.com/v1/places:searchText", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Goog-Api-Key": apiKey,
      "X-Goog-FieldMask": "places.location",
    },
    body: JSON.stringify({ textQuery: `${name} ${address}` }),
  });
  const data = await res.json();
  const loc = data.places?.[0]?.location;
  if (loc) {
    return { lat: parseFloat(loc.latitude.toFixed(4)), lng: parseFloat(loc.longitude.toFixed(4)) };
  }
  return { error: "NOT_FOUND" };
}

export default async (req, context) => {
  const apiKey = process.env.GOOGLE_PLACES_API_KEY;
  if (!apiKey) return new Response(JSON.stringify({ error: "No API key" }), { status: 500 });

  const results = {};
  for (const shop of shops) {
    results[shop.id] = await geocode(shop.name, shop.address, apiKey);
    await new Promise(r => setTimeout(r, 100));
  }

  return new Response(JSON.stringify(results, null, 2), {
    headers: { "Content-Type": "application/json" },
  });
};

export const config = { path: "/api/geocode-all" };
